### ISSUE TITLE
Scaling issues

### ISSUE THREAD

**Issue by darklinkpower** [felixkmh/StartPage-for-Playnite#1]
Using 125% DPI 1080p screen

Game covers don't fit the parent control

![image](https://user-images.githubusercontent.com/1389286/140325925-f381ab30-1d71-49a6-8e54-bdbb29082b11.png)

Also the tooltip seems to be cut when there are too many items in features

![image](https://user-images.githubusercontent.com/1389286/140326116-8d200b88-d2bd-4a1a-b4c5-689d551fcf52.png)

**Comment by felixkmh** [comment]
fixed game details overflowing via 5596d349ab9709ab8ef5cf72a536af1137a03148

**Comment by felixkmh** [comment]
fixed in v0.1.2
