### ISSUE TITLE
Shelves: Add option to use horizontal headers

### ISSUE THREAD

**Issue by darklinkpower** [felixkmh/StartPage-for-Playnite#100]
Currently the shelves use vertical text, which I think is difficult to read and also can be cut if there's not enough space available

![image](https://user-images.githubusercontent.com/1389286/164873765-d1d21ea2-baab-43d6-bf36-cca0c6d16214.png)

An example of horizontal text can be seen in Galaxy 2.0

![image](https://user-images.githubusercontent.com/1389286/164873832-2cfab9b8-eee0-4b02-b01d-313aba466ad6.png)

**Comment by felixkmh** [comment]
done via d44ff68018fa2f078779df660d1e681dfbe8c5e5

**Comment by darklinkpower** [comment]
Thanks!
