### ISSUE TITLE
Wrong game in All Time

### ISSUE THREAD

**Issue by OsoaGH** [felixkmh/StartPage-for-Playnite#105]
![image](https://user-images.githubusercontent.com/33041004/164896879-1415390e-d051-42b6-bb36-8b5fc4c9201a.png)
![image](https://user-images.githubusercontent.com/33041004/164896896-72ebaaf6-04cd-47e1-998e-0622cde79fb3.png)

May be caused by artificially adding playtime to Minecraft, instead of it being added up through all the sessions?

**Comment by felixkmh** [comment]
fixed via 7db24ccec9bc7121fd4e7f8d58f07747b08a17a4
