### ISSUE TITLE
Weekly Activity bars not showing playtime. Tooltip is working

### ISSUE THREAD

**Issue by DrAlexander11** [felixkmh/StartPage-for-Playnite#107]
Version 2.1.0
All bars are at minimum even though there is playtime to show.

**Comment by felixkmh** [comment]
If the vertical alignment is set to anything but stretch for this view, this is expected. If you want to control the height of it, you can create an empty panel above or below.

**Comment by DrAlexander11** [comment]
OK. Thanks for the clarification. I've set it to stretch and it's working.
