### ISSUE TITLE
Game Shelves: Horizontal Alignment Left, Right or Center makes the games disappear

### ISSUE THREAD

**Issue by DrAlexander11** [felixkmh/StartPage-for-Playnite#108]
Version 2.1.0
Stretch horizontal alignment works fine.
Aligning the games other than Stretch probably makes them very small, or something like that. They appear to move in the alignment direction and then disappear.

**Comment by felixkmh** [comment]
This is because the shelves never demand any space. It always trys to fill its parent. By setting it to anything but stretch for the vertical direction, the parent no longer fills the whole panel, and thus the shelves collapse.

**Comment by DrAlexander11** [comment]
OK. Thanks for the clarification.
