### ISSUE TITLE
Setting to add padding to the view

### ISSUE THREAD

**Issue by darklinkpower** [felixkmh/StartPage-for-Playnite#112]
As a suggestion, the view could use some padding to improve the layout and to make sure elements don't overlap with the window buttons with certain alignment options. Maybe it could be a setting, with a minimum padding  (20 is what I usually use for views, so maybe that could work?) and have a setting to configure this value to the user preference.

![image](https://user-images.githubusercontent.com/1389286/165017132-6f87718b-6a05-4ca1-91eb-f9b9a60ac9f7.png)

**Comment by felixkmh** [comment]
I added the option to set the padding uniformly for each view via 104835590ed2af3703b5e94d247097c6aa60d703. For getting some padding at the top for example, you can simply add an empty panel there.

**Comment by darklinkpower** [comment]
Thanks! If I understand right, this padding will apply to each added view (like shelves, clock, etc)? Sorry if I wasn't clear but I was thinking padding for all the view in general
