### ISSUE TITLE
Possible improvement when database changes and shelves are updated

### ISSUE THREAD

**Issue by darklinkpower** [felixkmh/StartPage-for-Playnite#113]
I have an extension that hides games. After invoking the function to hide the games, Playnite freezed for several second. This doesn't happen if the current view is Playnite library.

I'm not familiar with how the extension works and was wondering if perhaps the extension updates the shelves on each game update event. As a possible fix, a timer could be used to only update after no new events are being received. Something like this:

Game update event 1 -> `timer.Stop(); Timer.Start();` -> Game update event 2 -> `timer.Stop(); Timer.Start();` ->Timer_Tick (Updates shelves)

**Comment by felixkmh** [comment]
done via b62667df3b0c25cc1e50ad13a8710276b77a1aeb

**Comment by darklinkpower** [comment]
Thanks. I took a quick look and I think the `Stop()` method call should be done first on the event, otherwise the timer will keep running and there could be a race issue where the event is called again unnecessarily and also there's no reason to keep it running while the method has already been called

![image](https://user-images.githubusercontent.com/1389286/165027091-5abe41cc-bafc-4ffb-a807-eaa3e071848c.png)

**Comment by felixkmh** [comment]
yeah, makes sense.
