### ISSUE TITLE
Make Game Shelves settings specific to instance

### ISSUE THREAD

**Issue by darklinkpower** [felixkmh/StartPage-for-Playnite#129]
Currently the settings apply globally to all Game Shelves instance. I think it could be better if it applied individually. To provide an example, I have set a maximum width so the covers use the width for my screen for the panel in the lower side but since the setting applies globally, it also affects the panel on the upper left side:

![image](https://user-images.githubusercontent.com/1389286/166207133-a984d587-d7bd-42e1-ac33-8c0a1fb540aa.png)

This is what I could achieve if settings were instance specific:

![image](https://user-images.githubusercontent.com/1389286/166207590-142ab9bb-5e63-4e2a-9583-696cdc683d1e.png)

These are the settings that I think could be made instance specific:

![image](https://user-images.githubusercontent.com/1389286/166206903-4d66fd2c-2a23-413c-8f96-fe34f605ee03.png)

**Comment by chocolatechipcats** [comment]
Agreed; I wanted to do something similar myself.

**Comment by felixkmh** [comment]
done via 7bad423c6a713bf4f45ee2ad35cadde89dca3017. But the down scaling option is not included as a per shelve option, as the resolution depends on the max cover width of each shelve anyway.
