### ISSUE TITLE
Last Played: Covers clipping

### ISSUE THREAD

**Issue by chocolatechipcats** [felixkmh/StartPage-for-Playnite#137]
If the pane isn't wide enough to accommodate the selected number of covers, it truncates like so:

![2022-05-07 22_26_56-Playnite](https://user-images.githubusercontent.com/47759676/167277976-d7a5671c-23eb-4453-ad6c-bc30d52482b5.png)

Preferably, it would resize the covers instead.

Thank you!

**Comment by felixkmh** [comment]
done via d11ad7b5939031fe67fcf25b43e6c7cf7c88c873
