### ISSUE TITLE
Enhancement Requests: Additional options for "Most Played" view

### ISSUE THREAD

**Issue by chocolatechipcats** [felixkmh/StartPage-for-Playnite#144]
A few ideas that I think would make it more useful; take or leave as you will.

1. The option to display the second or thirdmost most played game for a specific period. 
2. Along with that, the option to either display more than 3 games at a time, or have multiple 'most played' views with separate settings.

Thanks.

**Comment by blackparadox** [comment]
I like these ideas, and I think that automatically picking the second, third etc with a "exclude games that have already appeared" option (like the shelves have) would be good too. That way if your currently playing your most played game of all time, it's not filling the panel with that one game.

**Comment by felixkmh** [comment]
done in 2.7.0
