### ISSUE TITLE
Incorrect "Date string" shown for recent played

### ISSUE THREAD

**Issue by da3ch1r** [felixkmh/StartPage-for-Playnite#151]
**Playnite Version**: 9.18
**Startpage Version**: 2.7.0

Hi there,

just recently I found that  the Startpage date string ('Today','Yesterday',etc.) are not correctly updated. It all works fine when Playnite is started, but when it runs 24h+ the day changed and it should update the labels. The update process worked correctly in previous versions, but I cannot say in which one(s), but now I may have multiple 'Today' strings shown. Interesting the games shown are sorted correctly, only the label is incorrect.

I'll append some screenshots when I have the time. (Did updates this morning so everything's ok right now)

**Comment by felixkmh** [comment]
done via fd8a88142e2ed33daa1380c2f28f4cea2c87bbe0
