### ISSUE TITLE
Enhancement Request: Don't show hidden games in Most Played

### ISSUE THREAD

**Issue by chocolatechipcats** [felixkmh/StartPage-for-Playnite#166]
I have a game playtesting that's NDA'd, so I set it to hidden  -- but it still shows up on StartPage through the Most Played widget. 

Unless I missed it somewhere, an option to _not_ show these games would be appreciated.

Thanks in advance. :)

**Comment by felixkmh** [comment]
There is a way. You can enable the option to create [SPG] tags when Playnite launches. You can assign such a tag to the game that you want to ignore. Just be aware that the most played view only updates if the player actitvity is updated (or Playnite restarts.)

**Comment by felixkmh** [comment]
done via 3826cb19f9698868e8e068cb09774e0ce1fb6a19
