### ISSUE TITLE
Enhancement Request: Most Played: Duplicated labels

### ISSUE THREAD

**Issue by chocolatechipcats** [felixkmh/StartPage-for-Playnite#173]
On my StartPage, I have a widget showing the three most played games in the last week. However, all three show the 'last week' label:

![2022-09-03 16_26_39-Window](https://user-images.githubusercontent.com/47759676/188285237-361fe88b-663b-4142-b995-9c5f49ab1ec4.png)

While definitely not a huge priority, it'd be appreciated if it could only show the label once.

Thank you!

**Comment by felixkmh** [comment]
done via d134c096eca36b38affe3b3776f52a0d9e4f38c4
