### ISSUE TITLE
[Request]Mutable videos when hovering over a game

### ISSUE THREAD

**Issue by Kinc4id** [felixkmh/StartPage-for-Playnite#198]
Whenever the mouse rests on a game a trailer plays blasting sound. Please add a setting to mute these completely.

**Comment by felixkmh** [comment]
There already is an option to set the trailer volume. You can access a volume slider by entering edit mode (right-click in an empty area and then enter edit mode). There should be a gear icon in the corner of each shelves view.

**Comment by Kinc4id** [comment]
That slider already is set to 0. Moving it doesn't change the volume at all.

![grafik](https://github.com/felixkmh/StartPage-for-Playnite/assets/5131586/e2769c3e-50a6-4b57-9a9b-8b27629bf21c)
