### ISSUE TITLE
Scrolling causes Playnite to freeze

### ISSUE THREAD

**Issue by darklinkpower** [felixkmh/StartPage-for-Playnite#2]
Using the horizontal scrollbar for games causes Playnite to freeze and increase CPU usage. Unfortunately nothing shows in the logs

![image](https://user-images.githubusercontent.com/1389286/140326404-484bc7ba-4473-4880-9f6a-2f0a3eb28d6b.png)

![image](https://user-images.githubusercontent.com/1389286/140326677-3e16a905-e998-4ed1-81d9-9e0a768170c6.png)

**Comment by felixkmh** [comment]
Probably due to the same issue in #4

**Comment by felixkmh** [comment]
Weirdly this kind of freeze only happens with scaling set to something other than 100%.

**Comment by felixkmh** [comment]
fixed via fac01bc4a878f4448d9e3ce72530f92e88a4d51b
