### ISSUE TITLE
unrecoverable error

### ISSUE THREAD

**Issue by triadne** [felixkmh/StartPage-for-Playnite#203]
This is the second time this has happened, and last time I fixed it but I do not know how. This time, I literally did nothing, I started my computer and now this happens and I have to disable start page. 
what am I supposed to do? I can't open the data folder, the link doesn't work and I'm certainly not wanting to delete all those data folders since I can't identify the startpage data folder among all those random folder names and I don't want to lose all the data for the other addons that are just fine.

[startpagelog.zip](https://github.com/felixkmh/StartPage-for-Playnite/files/12378997/startpagelog.zip)

**Comment by stepan323446** [comment]
1. close playnite if open in background
2. Go to directory `C:\Users\{username}\AppData\Local\Playnite` or another where your Playnite is installed
3. run `Safe Mode.bat`
4. You will open clear Playnite, where all themes and plugins do not work. Now you can go to settings and disable the desired extension

**Comment by triadne** [comment]
not helpful. playnite asks to disable the addon by default, and none of that helps me to fix the issue and allow me to enable startpage again.

startpage produces an unrecoverable error, which forces me to disable startpage in order to start playnite. I open playnite with startpage disabled and am without any recourse to fix startpage. with startpage disabled, I cannot find the data folder because the link to the data folder in playnite does not work. How do I either a) fix startpage or b) reset startpage. without knowing which data folder is the startpage data folder, how do i reset startpage? The only way to do so would be to delete all data folders and that would mess up my entire setup. why is the startpage folder not named sensibly? all these data folders are named random strings.

**Comment by felixkmh** [comment]
These folders are created by Playnite, according to the Plugin's Id, which is a Guid. StartPages Id is `a6a3dcf6-9bfe-426c-afb0-9f49409ae0c5` so there should be a folder with that name. To help me fix that issue, you could send me the contents of this folder.

**Comment by stepan323446** [comment]
> Не помогает. Playnite просит отключить аддон по умолчанию, и ничто из этого не помогает мне решить проблему и позволить мне снова включить StartPage.
> 
> StartPage выдает неустранимую ошибку, которая вынуждает меня отключить StartPage, чтобы запустить Playnite. Я открываю playnite с отключенной стартовой страницей и не могу исправить стартовую страницу. с отключенной стартовой страницей я не могу найти папку данных, потому что ссылка на папку данных в playnite не работает. Как мне либо а) исправить стартовую страницу, либо б) сбросить стартовую страницу. Не зная, какая папка данных является папкой данных StartPage, как сбросить StartPage? Единственный способ сделать это - удалить все папки с данными, и это испортит всю мою установку. Почему папка Startpage названа неразумно? Все эти папки данных называются случайными строками.



> not helpful. playnite asks to disable the addon by default, and none of that helps me to fix the issue and allow me to enable startpage again.
> 
> startpage produces an unrecoverable error, which forces me to disable startpage in order to start playnite. I open playnite with startpage disabled and am without any recourse to fix startpage. with startpage disabled, I cannot find the data folder because the link to the data folder in playnite does not work. How do I either a) fix startpage or b) reset startpage. without knowing which data folder is the startpage data folder, how do i reset startpage? The only way to do so would be to delete all data folders and that would mess up my entire setup. why is the startpage folder not named sensibly? all these data folders are named random strings.

Hmm. I just disabled StartPage via Playnite's safe mode. most recently had a problem with this.

Disabled other plugins, but only StartPage has a problem with this. The problem is that when you enter playnite, the start page opens and there is an endless loading, while the program stops responding. After a while, Playnite automatically closes.
