### ISSUE TITLE
Update available after every update

### ISSUE THREAD

**Issue by tynansdtm** [felixkmh/StartPage-for-Playnite#205]
Playnite wants to upgrade from 2.12.6 to 2.12.16 on every startup, even after updating.

![image](https://github.com/felixkmh/StartPage-for-Playnite/assets/19171387/b9da33cb-1269-4626-9c79-ab2867a2b7d6)

**Comment by felixkmh** [comment]
An error in the installer manifest. It should be 2.12.6. Wait a few minutes and update again.
