### ISSUE TITLE
StartPage crashes

### ISSUE THREAD

**Issue by Cerates** [felixkmh/StartPage-for-Playnite#25]
I just updated to the newest StartPage version and it crashes instantly when I press the StartPage button on the left sidebar. I don't know exactly if it worked before as I didn't try it yet. Log is attached:

[playnite-log.zip](https://github.com/felixkmh/StartPage-for-Playnite/files/7533908/playnite-log.zip)

**Comment by felixkmh** [comment]
should be fixed with v1.4.1.

**Comment by Cerates** [comment]
Wow so fast thanks 👍
