### ISSUE TITLE
Text layout suggestion

### ISSUE THREAD

**Issue by darklinkpower** [felixkmh/StartPage-for-Playnite#3]
In my opinion have the text sideways is not ideal so as a suggestion, having the sections text horizontal like this and increasing its size by using a larger font could work

![image](https://user-images.githubusercontent.com/1389286/140327858-70dc81fb-5abb-4f1c-a4fa-9b053589d41b.png)

**Comment by felixkmh** [comment]
I might consider it for the achievements, but for the game rows I feel like that would be a waste of vertical space. The spacing between the rows would be too big for my liking.

**Comment by darklinkpower** [comment]
Personally I'm not a fan of the idea of vertical text since it's counterintuitive and not a good UI practice in my opinion but I totally understand if you prefer it that way. I don't think the horizontal text should be seen as waste of space, proper spacing and text size helps it provide better hierarchy between elements and sections and could improve the layout.


Just for reference, here are some examples of start page using an approach like I suggested

Steam:

![image](https://user-images.githubusercontent.com/1389286/142700167-94bdc68e-c44a-4c34-b22c-52f091cc4ec1.png)

Origin:
![image](https://user-images.githubusercontent.com/1389286/142700313-f84fae38-892e-4f07-bee1-8424100ef811.png)


GOG Galaxy 2:
![image](https://user-images.githubusercontent.com/1389286/142700390-8149c62a-0487-4e06-b4e8-530971a64ea1.png)
