### ISSUE TITLE
Crash when clicking on Startpage button in sidebar (1.4.4)

### ISSUE THREAD

**Issue by Andei** [felixkmh/StartPage-for-Playnite#30]
`16-11 14:51:34.723|ERROR|PlayniteApplication:Unhandled exception occured.
System.Windows.Markup.XamlParseException: Beim Festlegen der Eigenschaft "System.Windows.FrameworkElement.Style" wurde eine Ausnahme ausgelöst. ---> System.InvalidOperationException: Nicht alle Eigenschaftsverweise im Eigenschaftspfad "RenderTransform.Y" können aufgelöst werden. Stellen Sie sicher, dass geeignete Objekte die Eigenschaften unterstützen.
   bei System.Windows.Media.Animation.Storyboard.VerifyPathIsAnimatable(PropertyPath path)
   bei System.Windows.Media.Animation.Storyboard.ClockTreeWalkRecursive(Clock currentClock, DependencyObject containingObject, INameScope nameScope, DependencyObject parentObject, String parentObjectName, PropertyPath parentPropertyPath, HandoffBehavior handoffBehavior, HybridDictionary clockMappings, Int64 layer)
   bei System.Windows.Media.Animation.Storyboard.ClockTreeWalkRecursive(Clock currentClock, DependencyObject containingObject, INameScope nameScope, DependencyObject parentObject, String parentObjectName, PropertyPath parentPropertyPath, HandoffBehavior handoffBehavior, HybridDictionary clockMappings, Int64 layer)
   bei System.Windows.Media.Animation.Storyboard.BeginCommon(DependencyObject containingObject, INameScope nameScope, HandoffBehavior handoffBehavior, Boolean isControllable, Int64 layer)
   bei System.Windows.Media.Animation.BeginStoryboard.Begin(DependencyObject targetObject, INameScope nameScope, Int64 layer)
   bei System.Windows.Media.Animation.BeginStoryboard.Invoke(FrameworkElement fe, FrameworkContentElement fce, Style targetStyle, FrameworkTemplate frameworkTemplate, Int64 layer)
   bei System.Windows.StyleHelper.InvokeActions(TriggerBase triggerBase, DependencyObject triggerContainer, TriggerActionCollection actions, Style style, FrameworkTemplate frameworkTemplate)
   bei System.Windows.StyleHelper.InvokeEnterOrExitActions(TriggerBase triggerBase, Boolean oldState, Boolean newState, DependencyObject triggerContainer, Style style, FrameworkTemplate frameworkTemplate)
   bei System.Windows.StyleHelper.InvokePropertyTriggerActions(TriggerBase triggerBase, DependencyObject triggerContainer, DependencyProperty changedProperty, DependencyPropertyChangedEventArgs changedArgs, Int32 sourceChildIndex, Style style, FrameworkTemplate frameworkTemplate)
   bei System.Windows.StyleHelper.OnTriggerSourcePropertyInvalidated(Style ownerStyle, FrameworkTemplate frameworkTemplate, DependencyObject container, DependencyProperty dp, DependencyPropertyChangedEventArgs changedArgs, Boolean invalidateOnlyContainer, FrugalStructList`1& triggerSourceRecordFromChildIndex, FrugalMap& propertyTriggersWithActions, Int32 sourceChildIndex)
   bei System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   bei System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   bei System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   bei System.Windows.StyleHelper.ApplyStyleOrTemplateValue(FrameworkObject fo, DependencyProperty dp)
   bei System.Windows.StyleHelper.InvalidateContainerDependents(DependencyObject container, FrugalStructList`1& exclusionContainerDependents, FrugalStructList`1& oldContainerDependents, FrugalStructList`1& newContainerDependents)
   bei System.Windows.StyleHelper.DoStyleInvalidations(FrameworkElement fe, FrameworkContentElement fce, Style oldStyle, Style newStyle)
   bei System.Windows.StyleHelper.UpdateStyleCache(FrameworkElement fe, FrameworkContentElement fce, Style oldStyle, Style newStyle, Style& styleCache)
   bei System.Windows.FrameworkElement.OnStyleChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
   bei System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   bei System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   bei System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   bei System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   bei System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   bei System.Windows.Baml2006.WpfKnownMemberInvoker.SetValue(Object instance, Object value)
   bei MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(XamlMember member, Object obj, Object value)
   bei MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   bei System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   bei System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   bei System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   bei LandingPage.Views.LandingPageView.InitializeComponent() in D:\Programmierung\playnite-dev\LandingPage\source\Views\LandingPageView.xaml:Zeile 1.
   bei LandingPage.Views.LandingPageView..ctor(LandingPageViewModel model) in D:\Programmierung\playnite-dev\LandingPage\source\Views\LandingPageView.xaml.cs:Zeile 37.
   bei LandingPage.LandingPageExtension.get_View() in D:\Programmierung\playnite-dev\LandingPage\source\LandingPageExtension.cs:Zeile 44.
   bei LandingPage.LandingPageExtension.ViewOpened() in D:\Programmierung\playnite-dev\LandingPage\source\LandingPageExtension.cs:Zeile 103.
   bei Playnite.DesktopApp.ViewModels.SidebarWrapperItem.Activation(Object arg) in C:\projects\playnite\source\Playnite.DesktopApp\ViewModels\DesktopAppViewModel_Sidebar.cs:Zeile 130.
   bei Playnite.SDK.RelayCommand`1.Execute(Object parameter) in C:\projects\playnite\source\PlayniteSDK\RelayCommand.cs:Zeile 199.
   bei MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   bei System.Windows.Controls.Primitives.ButtonBase.OnClick()
   bei System.Windows.Controls.Button.OnClick()
   bei System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   bei System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   bei System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   bei System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   bei System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   bei System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   bei System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   bei System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   bei System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   bei System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   bei System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   bei System.Windows.Input.InputManager.ProcessStagingArea()
   bei System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   bei System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   bei System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   bei System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   bei System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   bei MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   bei MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   bei System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   bei System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   bei System.Windows.Application.RunDispatcher(Object ignore)
   bei System.Windows.Application.RunInternal(Window window)
   bei System.Windows.Application.Run(Window window)
   bei Playnite.DesktopApp.ProgramEntry.Main(String[] args) in C:\projects\playnite\source\Playnite.DesktopApp\ProgramEntry.cs:Zeile 61.
16-11 14:51:34.749|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ExtensionCrashHandlerWindowFactory
`

**Comment by felixkmh** [comment]
May I ask which Theme and other Extensions you are using?

**Comment by felixkmh** [comment]
Some people in the forum complained about issues when having the GameActivity extension installed. Do you have that installed?

**Comment by Andei** [comment]
Yep, GameActivity is installed. I tried SP with emixednite and default theme.

**Comment by Andei** [comment]
Disabling GA and SP works like a charm.
Really beautiful btw

**Comment by felixkmh** [comment]
Thanks 😄 Could you try if this version still crashes with GA enabled? If it does, I would like to see if the error message is different.
[felixkmh_StartPage_Plugin_1_4_4.zip](https://github.com/felixkmh/StartPage-for-Playnite/files/7547289/felixkmh_StartPage_Plugin_1_4_4.zip)

**Comment by felixkmh** [comment]
Also, the playnite.log file should list all the extensions being loaded. Can you tell me whether GA or SP is loaded first?

**Comment by Andei** [comment]
No crash!

What do I have to do that SP shows at start up. Right now it only shows up if I click the sidebar button

`16-11 15:44:16.720|INFO |ExtensionFactory:Loaded plugin: DKG Theme Modifier, version 2.2.4
16-11 15:44:16.743|INFO |ExtensionFactory:Loaded plugin: Epic Store library integration, version 2.5
16-11 15:44:16.771|INFO |ExtensionFactory:Loaded plugin: Extra Metadata Loader, version 1.20
16-11 15:44:16.799|INFO |ExtensionFactory:Loaded plugin: DuplicateHider, version 3.7.1
16-11 15:44:16.827|INFO |ExtensionFactory:Loaded plugin: StartPage, version 1.4.4
16-11 15:44:16.827|INFO |ExtensionFactory:Loaded plugin: Friendly Set Playtime, version 0.2
16-11 15:44:16.842|INFO |ExtensionFactory:Loaded plugin: GOG library integration, version 2.4
16-11 15:44:16.855|INFO |ExtensionFactory:Loaded plugin: IGDB metadata provider, version 2.3
16-11 15:44:16.865|INFO |ExtensionFactory:Loaded plugin: Ludusavi, version 0.6.0
16-11 15:44:16.865|INFO |ExtensionFactory:Loaded plugin: News Viewer, version 1.0
16-11 15:44:16.865|INFO |ExtensionFactory:Loaded plugin: Origin library integration, version 2.3
16-11 15:44:16.883|INFO |ExtensionFactory:Loaded plugin: PCGamingWiki Metadata Provider, version 0.3.1
16-11 15:44:16.981|INFO |ExtensionFactory:Loaded plugin: CheckLocalizations, version 2.0.3
16-11 15:44:17.018|INFO |ExtensionFactory:Loaded plugin: DescriptionEditor, version 2.0.2
16-11 15:44:17.071|INFO |ExtensionFactory:Loaded plugin: GameActivity, version 2.1.2
16-11 15:44:17.134|INFO |ExtensionFactory:Loaded plugin: HowLongToBeat, version 2.4
16-11 15:44:17.178|INFO |ExtensionFactory:Loaded plugin: IsThereAnyDeal, version 2.0
16-11 15:44:17.232|INFO |ExtensionFactory:Loaded plugin: LibraryManagement, version 2.2
16-11 15:44:17.277|INFO |ExtensionFactory:Loaded plugin: ScreenshotsVisualizer, version 2.1
16-11 15:44:17.352|INFO |ExtensionFactory:Loaded plugin: SuccessStory, version 2.4
16-11 15:44:17.438|INFO |ExtensionFactory:Loaded plugin: ThemeModifier, version 2.2.3
16-11 15:44:17.450|INFO |ExtensionFactory:Loaded plugin: Review Viewer, version 2.11
16-11 15:44:17.464|INFO |ExtensionFactory:Loaded plugin: Splash Screen, version 2.6
16-11 15:44:17.464|INFO |ExtensionFactory:Loaded plugin: Steam Description Cleaner, version 1.3
16-11 15:44:17.475|INFO |ExtensionFactory:Loaded plugin: SteamGridDB Metadata Provider, version 1.0
16-11 15:44:17.475|INFO |ExtensionFactory:Loaded plugin: Steam Launcher Utility, version 2.6
16-11 15:44:17.508|INFO |ExtensionFactory:Loaded plugin: Steam library integration, version 2.3
16-11 15:44:17.508|INFO |ExtensionFactory:Loaded plugin: Universal Steam Metadata, version 2.3
16-11 15:44:17.550|INFO |ExtensionFactory:Loaded plugin: Uplay library integration, version 2.2`

**Comment by felixkmh** [comment]
Okay, nice. I still have no idea how another extension would have an influence on that, but if it works it works, I guess.
You can click the settings button on the top right when the Start Page view is active and enable the first option and set it to "Start Page".
![grafik](https://user-images.githubusercontent.com/24227002/142008642-264804e9-b8a3-40cc-9768-4cc119167b00.png)

**Comment by Andei** [comment]
With GA enabled and SP launched at start, PN doesn't crash but closes itself.

**Comment by felixkmh** [comment]
God dammit. I thought I finally had it. There should still be some error logged in the planite.log file.
In the meantime you can try if this works? [felixkmh_StartPage_Plugin_1_4_5.zip](https://github.com/felixkmh/StartPage-for-Playnite/files/7547720/felixkmh_StartPage_Plugin_1_4_5.zip)
Do you know how to start planite in safe mode?

**Comment by Andei** [comment]
Still crashing with GA enabled and SP at start up

`16-11 16:43:22.955|ERROR|PlayniteApplication:Unhandled exception occured.
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei LiveCharts.Wpf.Components.ChartUpdater.UpdateFrequency(TimeSpan freq) in c:\Users\btord\Documents\Projects\LiveCharts\WpfView\Components\ChartUpdater.cs:Zeile 69.
   bei LiveCharts.Wpf.Charts.Base.Chart.UpdateChartFrequency(DependencyObject o, DependencyPropertyChangedEventArgs e) in c:\Users\btord\Documents\Projects\LiveCharts\WpfView\Charts\Base\Chart.cs:Zeile 1446.
   bei System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   bei System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   bei System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   bei System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   bei System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   bei System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   bei System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   bei System.Windows.Data.BindingExpression.ScheduleTransfer(Boolean isASubPropertyChange)
   bei MS.Internal.Data.ClrBindingWorker.NewValueAvailable(Boolean dependencySourcesChanged, Boolean initialValue, Boolean isASubPropertyChange)
   bei MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   bei MS.Internal.Data.ClrBindingWorker.OnSourcePropertyChanged(Object o, String propName)
   bei MS.Internal.Data.PropertyPathWorker.OnPropertyChanged(Object sender, PropertyChangedEventArgs e)
   bei System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   bei System.ComponentModel.PropertyChangedEventManager.OnPropertyChanged(Object sender, PropertyChangedEventArgs args)
   bei System.Collections.Generic.ObservableObject.OnPropertyChanged(String name) in C:\projects\playnite\source\PlayniteSDK\Collections\ObservableObject.cs:Zeile 37.
   bei GameActivity.Controls.PluginChartLog.SetDefaultDataContext() in D:\GitHub\Lacro59\playnite-gameactivity-plugin\source\Controls\PluginChartLog.xaml.cs:Zeile 208.
   bei CommonPluginsShared.Controls.PluginUserControlExtend.GameContextChanged(Game oldContext, Game newContext) in D:\GitHub\Lacro59\playnite-gameactivity-plugin\source\playnite-plugincommon\CommonPluginsShared\Controls\PluginUserControlExtend.cs:Zeile 29.
   bei CommonPluginsShared.Controls.PluginUserControlExtendBase.PluginSettings_PropertyChanged(Object sender, PropertyChangedEventArgs e) in D:\GitHub\Lacro59\playnite-gameactivity-plugin\source\playnite-plugincommon\CommonPluginsShared\Controls\PluginUserControlExtendBase.cs:Zeile 102.
   bei GameActivity.Controls.PluginChartLog.<.ctor>b__50_2() in D:\GitHub\Lacro59\playnite-gameactivity-plugin\source\Controls\PluginChartLog.xaml.cs:Zeile 179.
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   bei System.Windows.Threading.DispatcherOperation.InvokeImpl()
   bei System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   bei MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Windows.Threading.DispatcherOperation.Invoke()
   bei System.Windows.Threading.Dispatcher.ProcessQueue()
   bei System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   bei System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   bei MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   bei MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   bei System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   bei System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   bei System.Windows.Application.RunDispatcher(Object ignore)
   bei System.Windows.Application.RunInternal(Window window)
   bei System.Windows.Application.Run(Window window)
   bei Playnite.DesktopApp.ProgramEntry.Main(String[] args) in C:\projects\playnite\source\Playnite.DesktopApp\ProgramEntry.cs:Zeile 61.
16-11 16:43:22.964|DEBUG|WindowFactory:Show dialog window Playnite.Windows.ExtensionCrashHandlerWindowFactory
`

**Comment by felixkmh** [comment]
How about this
[felixkmh_StartPage_Plugin_1_4_5.zip](https://github.com/felixkmh/StartPage-for-Playnite/files/7547865/felixkmh_StartPage_Plugin_1_4_5.zip)

**Comment by Andei** [comment]
Still crashing

**Comment by Andei** [comment]
Still crashing when launch view is enabled. Manually switching is no problem.

That would be a pitty. No support on Discord for this problem avaiable?

**Comment by felixkmh** [comment]
This feature, as stated, is not really supported by the PlayniteAPI or its dev. Basically, all I do is programmatically press the side bar button. For some reason that causes an error in some component of GameActivity, maybe because it didn't finish initializing something (the strange thing here is that it does not happen for everyone, for me it works just fine). What I could do from my side, is adding an delay, and just wait some time before switching. The problem with that is that I wouldn't know how long that needs to be, so I would need to make it fairly long (I set it to 6s here: [felixkmh_StartPage_Plugin_1_4_6.zip](https://github.com/felixkmh/StartPage-for-Playnite/files/7548360/felixkmh_StartPage_Plugin_1_4_6.zip), you can try if that would work). At this point you might as well have clicked that button yourself in that time.
The other option is to go to GA's dev (https://github.com/Lacro59/playnite-gameactivity-plugin), and ask if that can be fixed there.

**Comment by Andei** [comment]
Interesting! So you have GA installed too, but there's no crash?

**Comment by felixkmh** [comment]
I did have that exact error at some point (which is different than the one this issue started with), when the priority I mentioned before was set to a high value and someone reported a crash. The log is similar to what you posted. Hence I lowered the priority and it worked since.

**Comment by tlneondo** [comment]
Also having crashing issues
[crash.zip](https://github.com/felixkmh/StartPage-for-Playnite/files/7557219/crash.zip)

**Comment by felixkmh** [comment]
@tlneondo, that crash is a separate issue. It should be fixed via c34f547afca3e27dcaf4bd9ce302f60e9a696184.
