### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by darklinkpower** [felixkmh/StartPage-for-Playnite#4]
Unfortunately my igpu really struggles with blur and certain effects in WPF. My igpu is an intel HD4600.

I don't know what could be done about this, maybe allow to reduce or disable the blur or the more complicated option to implement a faster blur method. 

If you don't care about being able to see certain details of the game background image and just want the colors, I use a custom background blur solution made by Fuene in a theme that doesn't cause any performance impact and is pretty fast: https://github.com/darklinkpower/Helium/blob/master/source/Views/DetailsViewGameOverview.xaml#L18-L82

It looks like this but could be tuned up to produce different results by changing the opacity or other properties

![image](https://user-images.githubusercontent.com/1389286/140328810-ccae9ed6-1188-44f9-99bb-b3d8a4297cf4.png)

**Comment by darklinkpower** [comment]
This is how it looks by changing the border opacity to `1.0`

![image](https://user-images.githubusercontent.com/1389286/140330657-a7d6ecd3-7003-4f88-904a-371d14144e9c.png)

**Comment by felixkmh** [comment]
fixed via 1c798d7f3c42cd64414474fbb4791083e2cbc709
