### ISSUE TITLE
Date string overlaps with time string

### ISSUE THREAD

**Issue by xiSage** [felixkmh/StartPage-for-Playnite#42]
- version: 1.72
- Playnite version: 9.6
- Playnite language: Simplified Chinese
- system language: Simplified Chinese
![image](https://user-images.githubusercontent.com/57551864/142751731-373ea314-19e3-47be-9209-5cbc8c033d9e.png)

**Comment by felixkmh** [comment]
May I ask which font you are using?

**Comment by felixkmh** [comment]
fixed via 5c17659af2da2df59e04577a2730995c10af81c9
