### ISSUE TITLE
Status bar on Start page

### ISSUE THREAD

**Issue by Vackz** [felixkmh/StartPage-for-Playnite#43]
![image](https://user-images.githubusercontent.com/77805160/143052992-20d279c1-bf03-4408-9415-3f0bf5d6b5f7.png)

**Comment by felixkmh** [comment]
done via 41d0b6f4655e69494e724a4a0500af1ac2961bc3. But it is again kind of hacky because its not officially supported to do it, so I cannot guarantee it will work as expected.
