### ISSUE TITLE
Option to change Most Played to Most Played Recently

### ISSUE THREAD

**Issue by Super1337Boy** [felixkmh/StartPage-for-Playnite#51]
I'm hoping it would be possible to add an option to change the Most Played game to show the Most Played Recently instead. 

The game I've played the most is not a game I'm playing these days, and it's not a play time I'm likely to beat any time soon.

It would be more useful for me to see the game I've played the most during the last week, month or even year instead. (Different options for time inteval would be even more welcome here).

**Comment by Andei** [comment]
Or maybe an option for Last Month-->Last Year-->All time

**Comment by felixkmh** [comment]
done in v2.0.0
