### ISSUE TITLE
Instant crash after updating GameActivity.

### ISSUE THREAD

**Issue by NatParable** [felixkmh/StartPage-for-Playnite#52]
StartPage (1.9.2) seems to be incompatible with the most recent update of GameActivity (2.4). If both are enabled, and if StartPage is set to show GameActivity data, Playnite will crash immediately upon loading.

**Comment by felixkmh** [comment]
Please provide the playnite.log file.

**Comment by felixkmh** [comment]
It appears to be an error on the side of GameActivity. It only occurs if the option to switch to the StartPage view on launch is enabled.

**Comment by felixkmh** [comment]
Should be fixed with GameActivity 2.4.2
