### ISSUE TITLE
error  with start page extension 

### ISSUE THREAD

**Issue by Felzow47** [felixkmh/StartPage-for-Playnite#59]
System.ArgumentNullException: La valeur ne peut pas être null.
Nom du paramètre : source
   à System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   à LandingPage.ViewModels.LandingPageViewModel.IsRelevantUpdate(ItemUpdateEvent`1 update) dans D:\Programmierung\playnite-dev\LandingPage\source\ViewModels\LandingPageViewModel.cs:ligne 507
   à LandingPage.ViewModels.LandingPageViewModel.<>c.<Games_ItemUpdated>b__73_0(ItemUpdateEvent`1 u) dans D:\Programmierung\playnite-dev\LandingPage\source\ViewModels\LandingPageViewModel.cs:ligne 487

**Comment by felixkmh** [comment]
fixed in v1.9.5
