### ISSUE TITLE
[Enhancement Request] Allow multi-line shelves

### ISSUE THREAD

**Issue by chocolatechipcats** [felixkmh/StartPage-for-Playnite#66]
With only one shelf, there can be a lot of wasted vertical space. 

![2022-01-31 03_00_56-Playnite](https://user-images.githubusercontent.com/47759676/151751739-acd5037c-e644-4ac0-89da-72538cf4b47b.png)

Allowing a single shelf to overflow onto a second row would allow the user to display more games and not waste that space.

Thanks in advance.

**Comment by felixkmh** [comment]
done in v1.11.0
