### ISSUE TITLE
The games are not listed!

### ISSUE THREAD

**Issue by RedmineTV** [felixkmh/StartPage-for-Playnite#68]
Since the 1.11.0 update 
The Last Played and New added shelfs are gone
(I checked the options)
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/44092568/151844811-9c916e27-00ff-491a-a1d6-07f6128bb2ae.png">

**Comment by felixkmh** [comment]
Not sure why they disappeared, but you should be able to get them back by right clicking in an empty area and clicking on "Add Shelve". You can add as many as you want and customize them by clicking the settings icon that pops up if you move the mouse over the label of the shelve.

**Comment by RedmineTV** [comment]
thanks 
Btw love your Plugin
