### ISSUE TITLE
Option to Remove favorites from Recently Played List

### ISSUE THREAD

**Issue by tlneondo** [felixkmh/StartPage-for-Playnite#75]
![image](https://user-images.githubusercontent.com/12129080/153306627-3caa6b1c-e10b-4a0b-83fc-a7337a49baa5.png)

See Image. I love me some Blood, and Playnite actually works as a decent mod launcher for it. But I don't need double entries on the same page.

**Comment by felixkmh** [comment]
done via 6311ced8cf18e13d8c96a6190bd44e149aa4b9f6
