### ISSUE TITLE
[Enhancement Request] Option to ignore specific games for 'Most Played.' 

### ISSUE THREAD

**Issue by chocolatechipcats** [felixkmh/StartPage-for-Playnite#76]
I have an incremental/clicker game that I often like to leave running in the background. Unfortunately, this results in it dominating the most-played game slots on the start page. I'd appreciate an option to specifically ignore that game so it can show something different there.

It would also let me get rid of Windows Solitaire for the most-played of all-time, lol. 

Thank you.

**Comment by felixkmh** [comment]
done via 68c970ec4432f27d5c0499107970357172ff79fe
