### ISSUE TITLE
StartPage makes Playnite crash on startup

### ISSUE THREAD

**Issue by Driesmann** [felixkmh/StartPage-for-Playnite#79]
Hi,

Since a couple of weeks, StartPage began crashing my Playnite. Unfortunately this means I have to disable the extension for the time being.

Hope you find some time to look into it!

Kind regard.

[StartPage crash log.zip](https://github.com/felixkmh/StartPage-for-Playnite/files/8365510/StartPage.crash.log.zip)

**Comment by felixkmh** [comment]
If you open the library management (Ctrl+W), under Tags, do you see any tags starting with [SPG]? Like "[SPG] Ignore"? The log also shows that DuplicateHider crashes with a similar error related to adding tags. Is this also still an issue for you?

What's weird, is that it crashes in Playnites code, not in mine, maybe has something to do with it not being thread safe. But DuplicateHider shouldn't crash if that is the cause for StartPage crashing.

**Comment by felixkmh** [comment]
I attached a build that has synchronized access to the tags. Does it still crash with the same error? [felixkmh_StartPage_Plugin_1_14_0_DEBUG.zip](https://github.com/felixkmh/StartPage-for-Playnite/files/8365763/felixkmh_StartPage_Plugin_1_14_0_DEBUG.zip)

**Comment by Driesmann** [comment]
So I did the following:

- Uninstalled the normal extension and then reinstalled using the version you posted here. Still crashed.
- Removed all the tags (there were none with "[SPG] Ignore" though), still crashed.
- Turned off DuplicateHider, still crashed.

Here is the latest crash log: 
[StartPage crash log2.zip](https://github.com/felixkmh/StartPage-for-Playnite/files/8366041/StartPage.crash.log2.zip)

**Comment by felixkmh** [comment]
Just curious: can you add tags manually?

**Comment by felixkmh** [comment]
This build shouldn't crash. But if it still does, at least I should get some more useful information in the log. [felixkmh_StartPage_Plugin_1_14_0_DEBUG.zip](https://github.com/felixkmh/StartPage-for-Playnite/files/8366109/felixkmh_StartPage_Plugin_1_14_0_DEBUG.zip)

**Comment by Driesmann** [comment]
This version doesn't crash, but it takes a very long time to launch.

And yes, I can add tags manually. It launches both with and without tags.

**Comment by felixkmh** [comment]
So it probably still throws the same error over and over again. The difference being that I'm not letting it propagate and crash the whole application and logging every error. That would explain why it takes some time to launch. Once Playnite launched, try going to the library view and then back to the StartPage view. After that, check for any [SPG] tags again. If there are two, chances are the next time Playnite is launched, it won't take that long.
Also, there should be some errors logged in the extension.log file. That might be useful. The easiest way to find it would be to use the "Log Open" extension.

**Comment by Driesmann** [comment]
Checking the log extension, it is as you said. The same error over and over again. Playnite is also a lot slower now.

here is the file: 
[StartPage log.txt](https://github.com/felixkmh/StartPage-for-Playnite/files/8366339/StartPage.log.txt)


I have removed all my tags at this point, and going to library view and back to StartPage doesn't give me any [SPG] tags, so I'm unsure what to do now.

**Comment by felixkmh** [comment]
Sorry, maybe I should have clarified on that, but deleting tags other than [SPG] ones (which apparently never get created anyway), was never necessary. The reason I kept asking about those, was that Playnite simply crashes the moment StartPage tries to create those tags that are used to ignore certain games. Because StartPage request those tags when it's loaded, I checked whether it would be able to create those some time after Playnite was launched, by switching views, but that also does not seem to allow StartPage to create those tags. Other than opening an issue in @JosefNemec's Playnite repository, I'm not sure what to make of it either.
For now you can use the version with the tagging feature disabled:
[felixkmh_StartPage_Plugin_1_14_0_DEBUG.zip](https://github.com/felixkmh/StartPage-for-Playnite/files/8366427/felixkmh_StartPage_Plugin_1_14_0_DEBUG.zip)

**Comment by Driesmann** [comment]
No problem about the tags, I naively thought it might solve the issue.

The last version you sent works perfectly and without the slow loading. 

Thanks a lot for investigating and providing a solution!

**Comment by felixkmh** [comment]
One last thing I would like to confirm, if you don't mind. Does running this version create the tags without crashing
[felixkmh_StartPage_Plugin_1_14_0_DEBUG.zip](https://github.com/felixkmh/StartPage-for-Playnite/files/8366509/felixkmh_StartPage_Plugin_1_14_0_DEBUG.zip)
?

**Comment by Driesmann** [comment]
Just turned off my pc, I'll take a look tomorrow evening if that's fine for you.
