### ISSUE TITLE
Add way to remove added views

### ISSUE THREAD

**Issue by darklinkpower** [felixkmh/StartPage-for-Playnite#97]
Sorry if I'm wrong but I searched and I couldn't find a way to remove views or splited views
If there isn't, I think it could be added to the right click submenu 

![image](https://user-images.githubusercontent.com/1389286/164873247-beabf7ad-485c-4d2e-837f-ddfbcf7346ab.png)

**Comment by felixkmh** [comment]
You can merge panels by right-clicking on the Grid-Splitters.
