### ISSUE TITLE
Option to adjust height of extension view/allow to use more area

### ISSUE THREAD

**Issue by darklinkpower** [felixkmh/StartPage-for-Playnite#98]
Currently the extension view will use the height of the window. This can cause the area to be quite limited when:
1. Playnite is in windowed mode
2. Display has low resolution
3. DPI is high (125% or more for example)

Screenshot 1920x1080 125% DPI
![image](https://user-images.githubusercontent.com/1389286/164873376-6a94b850-166e-42ab-99e6-8633836fbacd.png)

![image](https://user-images.githubusercontent.com/1389286/164873455-b24e98fd-2a55-4fb6-a43c-d5c8c0b76256.png)

As an option, it could use a scrollviewer that allows to use more height than what the window has

**Comment by felixkmh** [comment]
done via cccf865f4e17b0ae6c956993835b861c4750c38e
