### ISSUE TITLE
Add option to adjust vertical and horizontal alignment of panel content

### ISSUE THREAD

**Issue by darklinkpower** [felixkmh/StartPage-for-Playnite#99]
Option to adjust vertical and horizontal alignment of panel content

Currently the available views seem to use different alignments. Considering that the views can be rearranged, I think the best solution is to allow to adjust the alignments

![image](https://user-images.githubusercontent.com/1389286/164873609-d8de0329-822b-4e82-842a-3dfd66ec8917.png)

**Comment by felixkmh** [comment]
done in a7f38870585d9e5e7b636704b50970fdefc5cc10
